task:
  name: mazeAMP
  headless: ${resolve_default:False,${..headless}}
  training_algo: AMP
  env:
    numEnvs: ${resolve_default:16,${...num_envs}}
    numAMPObsSteps: 2
    motion_file: custom_envs/data/maze_env/maze_motions.zarr
train:
  params:
    seed: ${...seed}
    algo:
      name: amp_continuous
    model:
      name: continuous_amp
    network:
      name: amp
      separate: true
      space:
        continuous:
          mu_activation: None
          sigma_activation: None
          mu_init:
            name: default
          sigma_init:
            name: const_initializer
            val: -3.0
          fixed_sigma: true
          learn_sigma: false
      mlp:
        units:
        - 1024
        - 512
        activation: relu
        d2rl: false
        initializer:
          name: default
        regularizer:
          name: None
      disc:
        units:
        - 1024
        - 512
        activation: relu
        initializer:
          name: default
        regularizer:
          name: None
    load_checkpoint: ${if:${...checkpoint},True,False}
    load_path: ${...checkpoint}
    config:
      name: ${resolve_default:mazeAMP,${....experiment}}
      full_experiment_name: ${.name}
      max_epochs: ${resolve_default:5000,${....max_iterations}}
      env_name: gym_env
      env_config:
        seed: ${resolve_default:-1,${.....seed}}
      ppo: true
      reward_shaper:
        scale_value: 1.0
      normalize_advantage: true
      normalize_input: true
      normalize_value: true
      value_bootstrap: true
      gamma: 0.99
      tau: 0.95
      num_actors: ${....task.env.numEnvs}
      multi_gpu: ${....multi_gpu}
      mixed_precision: false
      learning_rate: 5.0e-05
      score_to_win: 250
      save_best_after: 50
      save_frequency: 30
      grad_norm: 0.5
      entropy_coef: 0.0
      truncate_grads: false
      e_clip: 0.2
      clip_value: false
      print_stats: true
      horizon_length: 32
      minibatch_size: 16
      mini_epochs: 4
      critic_coef: 1
      lr_schedule: constant
      kl_threshold: 0.008
      seq_length: 4
      bounds_loss_coef: 0
      amp_obs_demo_buffer_size: 20000
      amp_replay_buffer_size: 10000
      amp_replay_keep_prob: 0.1
      amp_batch_size: 64
      amp_minibatch_size: 16
      disc_coef: 5
      disc_logit_reg: 0.05
      disc_grad_penalty: 10.0
      disc_reward_scale: 2
      disc_weight_decay: 0.0001
      normalize_amp_input: true
      task_reward_w: 1.0
      disc_reward_w: 0.0
      player:
        render: true
        visualise_disc: true
        render_sleep: 0.01
        games_num: 5
pbt:
  enabled: false
task_name: ${task.name}
experiment: ''
num_envs: 16
seed: 42
torch_deterministic: false
max_iterations: 1000
headless: false
physics_engine: physx
pipeline: gpu
sim_device: cuda:0
rl_device: cuda:0
graphics_device_id: 0
num_threads: 4
solver_type: 1
num_subscenes: 4
test: false
checkpoint: ''
sigma: ''
multi_gpu: false
wandb_activate: false
wandb_group: ''
wandb_name: ${train.params.config.name}
wandb_entity: ''
wandb_project: isaacgymenvs
wandb_tags: []
wandb_logcode_dir: ''
capture_video: false
capture_video_freq: 1464
capture_video_len: 100
force_render: true
