params:
  seed: ${...seed}
  
  algo:
    name: amp_continuous

  model:
    name: continuous_amp

  network:
    name: amp
    separate: True
    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: -2.9
        fixed_sigma: True
        learn_sigma: False
        
    mlp:
      units: [1024, 512]
      activation: relu
      d2rl: False
      
      initializer:
          name: default
      regularizer:
        name: None
        
    disc:
      units: [1024, 512]
      activation: relu

      initializer:
        name: default
      regularizer:
        name: None

  load_checkpoint: ${if:${...checkpoint},True,False} #Training checkpint. Set to True if the main config has a checkpoint given. Is irrelevant when playing policies
  load_path: ${...checkpoint} # path to the checkpoint to load

  config:
    name: ${resolve_default:pushTAMP,${....experiment}}
    full_experiment_name: ${.name}
    env_name:  gym_env
    # Gets passed on the the multi-env class
    env_config:
      seed: ${resolve_default:-1,${.....seed}}
    ppo: True
    multi_gpu: ${....multi_gpu}
    mixed_precision: False
    normalize_input: True
    normalize_value: True
    value_bootstrap: True
    num_actors: ${....task.env.numEnvs} # num_envs to run
    reward_shaper:
      scale_value: 1
    normalize_advantage: True
    gamma: 0.99
    tau: 0.95
    learning_rate: 5e-5
    lr_schedule:  constant
    kl_threshold: 0.008
    score_to_win: 25 # Training stops if reached
    max_epochs: ${resolve_default:5000,${....max_iterations}}
    save_best_after: 50
    save_frequency: 30
    print_stats: True
    grad_norm: 0.5
    entropy_coef: 0.0
    truncate_grads: False
    e_clip: 0.2
    horizon_length: 64
    minibatch_size: 32 # batch_size % minibatch_size == 0 | batch_size = horizon_len * num_actors * num_agents
    mini_epochs: 4
    critic_coef: 1
    clip_value: False
    seq_length: 4
    bounds_loss_coef: 0
    amp_obs_demo_buffer_size: 20000
    amp_replay_buffer_size: 10000
    amp_replay_keep_prob: 0.1
    amp_batch_size: 64
    amp_minibatch_size: 16 # amp_minibatch size <= minibatch_size 
    disc_coef: 5
    disc_logit_reg: 0.05
    disc_grad_penalty: 10.0
    disc_reward_scale: 2
    disc_weight_decay: 0.0001
    normalize_amp_input: True
    task_reward_w: 0.0
    disc_reward_w: 1.0
    
    player:
      render: True
      render_sleep: 0.1 # Determines frame rate (how many seconds to wait between two frames)
      games_num: 5 # Number of games to play
